vim.cmd("hi clear")
vim.cmd("syntax reset")
vim.g.colors_name = "mooschcolorscheme"
vim.o.background = "dark"

local hl = vim.api.nvim_set_hl

hl(0, "Normal", { fg = "#afb1b1", bg = "#14141b" })

hl(0, "DiffText", { fg = "#dddddd" })
hl(0, "ErrorMsg", { fg = "#dddddd" })
hl(0, "WarningMsg", { fg = "#dddddd" })
hl(0, "PreProc", { fg = "#dddddd" })
hl(0, "Exception", { fg = "#dddddd" })
hl(0, "Error", { fg = "#dddddd" })
hl(0, "DiffDelete", { fg = "#dddddd" })
hl(0, "GitGutterDelete", { fg = "#dddddd" })
hl(0, "GitGutterChangeDelete", { fg = "#dddddd" })
hl(0, "cssIdentifier", { fg = "#dddddd" })
hl(0, "cssImportant", { fg = "#dddddd" })
hl(0, "Type", { fg = "#dddddd" })
hl(0, "Identifier", { fg = "#dddddd" })

hl(0, "PMenuSel", { fg = "#f5e40f" })
hl(0, "Constant", { fg = "#f5e40f" })
hl(0, "Repeat", { fg = "#f5e40f" })
hl(0, "DiffAdd", { fg = "#f5e40f" })
hl(0, "GitGutterAdd", { fg = "#f5e40f" })
hl(0, "cssIncludeKeyword", { fg = "#f5e40f" })
hl(0, "Keyword", { fg = "#f5e40f" })

hl(0, "IncSearch", { fg = "#9c9c9a" })
hl(0, "Title", { fg = "#afb1b1" })
hl(0, "PreCondit", { fg = "#9c9c9a" })
hl(0, "Debug", { fg = "#9c9c9a" })
hl(0, "SpecialChar", { fg = "#9c9c9a" })
hl(0, "Conditional", { fg = "#9c9c9a" })
hl(0, "Todo", { fg = "#9c9c9a" })
hl(0, "Special", { fg = "#9c9c9a" })
hl(0, "Label", { fg = "#9c9c9a" })
hl(0, "Delimiter", { fg = "#9c9c9a" })
hl(0, "Number", { fg = "#9c9c9a" })
hl(0, "CursorLineNR", { fg = "#9c9c9a" })
hl(0, "Define", { fg = "#9c9c9a" })
hl(0, "MoreMsg", { fg = "#9c9c9a" })
hl(0, "Tag", { fg = "#9c9c9a" })
hl(0, "String", { fg = "#9c9c9a" })
hl(0, "MatchParen", { fg = "#9c9c9a" })
hl(0, "Macro", { fg = "#9c9c9a" })
hl(0, "DiffChange", { fg = "#9c9c9a" })
hl(0, "GitGutterChange", { fg = "#9c9c9a" })
hl(0, "cssColor", { fg = "#9c9c9a" })

hl(0, "Function", { fg = "#eeeeee" })
hl(0, "Directory", { fg = "#87878b" })
hl(0, "markdownLinkText", { fg = "#87878b" })
hl(0, "javaScriptBoolean", { fg = "#87878b" })
hl(0, "Include", { fg = "#87878b" })
hl(0, "Storage", { fg = "#87878b" })
hl(0, "cssClassName", { fg = "#87878b" })
hl(0, "cssClassNameDot", { fg = "#87878b" })

hl(0, "Statement", { fg = "#818585" })
hl(0, "Operator", { fg = "#818585" })
hl(0, "cssAttr", { fg = "#818585" })

hl(0, "Pmenu", { fg = "#afb1b1", bg = "#3e5d80" })
hl(0, "SignColumn", { bg = "#14141b" })
hl(0, "LineNr", { fg = "#494b4b", bg = "#14141b" })
hl(0, "NonText", { fg = "#a1a0a0", bg = "#14141b" })
hl(0, "Comment", { fg = "#a1a0a0", italic = true })
hl(0, "SpecialComment", { fg = "#a1a0a0", italic = true })
hl(0, "CursorLine", { bg = "#3e5d80" })
hl(0, "TabLineFill", { bg = "#3e5d80" })
hl(0, "TabLine", { fg = "#494b4b", bg = "#3e5d80" })
hl(0, "StatusLine", { fg = "#afb1b1", bg = "#3e5d80", bold = true })
hl(0, "StatusLineNC", { fg = "#afb1b1", bg = "#14141b" })
hl(0, "Search", { fg = "#afb1b1", bg = "#a1a0a0" })
hl(0, "VertSplit", { fg = "#3e5d80" })
hl(0, "Visual", { bg = "#3e5d80" })

hl(0, "SnacksIndent", { fg = "#252530" })
hl(0, "SnacksIndentScope", { fg = "#494b4b" })
